"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import type { CaptionDoc } from "@everyword/captions-core";
import { computeWordIndex, countWords } from "@everyword/captions-core";
import { KaraokeCaptions } from "karaoke-captions-react";
import { HeroDemo } from "../components/HeroDemo";
import { Developers } from "../components/Developers";
import { FireTv } from "../components/FireTv";
import { McpProof } from "../components/McpProof";
import { Privacy } from "../components/Privacy";
import { UpgradeProof } from "../components/UpgradeProof";
import { Faq } from "../components/Faq";
import { InfoButton } from "../components/InfoButton";

/**
 * The EveryWord reader.
 *
 * Real public-domain content, real word-timed captions generated by the
 * EveryWord pipeline (Amazon Transcribe), rendered karaoke style: words
 * light up as they are spoken, and watching quietly becomes reading.
 * This page is the same renderer the Fire TV app uses.
 */

interface ManifestItem {
  slug: string;
  title: string;
  attribution: string;
  media: string;
  captions: string;
  words: number;
  durationSec: number;
  source?: "polly" | "transcribe" | "aligned";
  /** "video" plays a picture. Anything else is audio with text. */
  kind?: "video" | "audio";
  /** For an upgraded track: the subtitle file the video already had. */
  sourceSubtitles?: string;
  /** For an upgraded track: how much of it anchored to recognised speech. */
  anchoredRate?: number;
}

const FONT_SIZES = ["1.6rem", "2.1rem", "2.7rem"];
const FONT_LABELS = ["Small", "Medium", "Large"];

const EVIDENCE = [
  {
    finding:
      "A five-year study of 13,000 people who could initially read little or nothing found 32 percentage points more children became good readers than in the unexposed group, and 9 points more adults. Newspaper reading rose from 33.7 to 70 percent. Cost: $0.004 per learner.",
    source:
      "Kothari and Bandyopadhyay, catalogued by the UNESCO Institute for Lifelong Learning",
    url: "https://www.uil.unesco.org/en/litbase/reading-billion-same-language-subtitling-india",
  },
  {
    finding:
      "More than 100 empirical studies find captions improve comprehension of, attention to, and memory for video, with people learning to read among those who gain most.",
    source: "Gernsbacher, Policy Insights from the Behavioral and Brain Sciences, 2015",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5214590/",
  },
  {
    finding:
      "54 percent of US adults aged 16 to 74, about 130 million people, read below a sixth grade level. The estimated cost to the economy is $2.2 trillion a year.",
    source: "Gallup for the Barbara Bush Foundation, 2020",
    url: "https://www.barbarabush.org/new-economic-study/",
  },
  {
    finding:
      "In 2023, 28 percent of US adults, 58.9 million people, scored at literacy Level 1 or below, up from 48 million in 2017. The problem is growing, not shrinking.",
    source: "OECD PIAAC Cycle 2, US results",
    url: "https://www.air.org/resource/report/highlights-us-piaac-cycle-2-results",
  },
];

function useTheme(): [string, () => void] {
  const [mode, setMode] = useState("system");
  useEffect(() => {
    try {
      const t = localStorage.getItem("ew-theme");
      if (t === "light" || t === "dark") setMode(t);
    } catch {
      /* storage unavailable */
    }
  }, []);
  const cycle = useCallback(() => {
    setMode((prev) => {
      const next = prev === "system" ? "light" : prev === "light" ? "dark" : "system";
      const root = document.documentElement;
      if (next === "system") root.removeAttribute("data-theme");
      else root.setAttribute("data-theme", next);
      try {
        if (next === "system") localStorage.removeItem("ew-theme");
        else localStorage.setItem("ew-theme", next);
      } catch {
        /* ignore */
      }
      return next;
    });
  }, []);
  return [mode, cycle];
}

export default function Reader() {
  const [library, setLibrary] = useState<ManifestItem[]>([]);
  const [item, setItem] = useState<ManifestItem | null>(null);
  const [doc, setDoc] = useState<CaptionDoc | null>(null);
  const [time, setTime] = useState(0);
  const [playing, setPlaying] = useState(false);
  const [slow, setSlow] = useState(false);
  const [fontIdx, setFontIdx] = useState(1);
  const [wordsRead, setWordsRead] = useState(0);
  const [duration, setDuration] = useState(0);
  const audioRef = useRef<HTMLVideoElement>(null);
  const rafRef = useRef(0);
  const [themeMode, cycleTheme] = useTheme();

  useEffect(() => {
    (async () => {
      const manifest = (await fetch("/content/manifest.json").then((r) => r.json())) as {
        items: ManifestItem[];
      };
      if (!manifest.items.length) return;
      setLibrary(manifest.items);
      const first = manifest.items[0]!;
      setItem(first);
      const captions = (await fetch(`/content/${first.captions}`).then((r) =>
        r.json(),
      )) as CaptionDoc;
      setDoc(captions);
    })().catch(() => setItem(null));
  }, []);

  /** Switching stories resets playback and the per-story reading meter. */
  const chooseStory = useCallback(
    async (next: ManifestItem) => {
      if (next.slug === item?.slug) return;
      const audio = audioRef.current;
      if (audio) audio.pause();
      setPlaying(false);
      setTime(0);
      setWordsRead(0);
      setDuration(0);
      setItem(next);
      const captions = (await fetch(`/content/${next.captions}`).then((r) =>
        r.json(),
      )) as CaptionDoc;
      setDoc(captions);
    },
    [item?.slug],
  );

  // Smooth time updates while playing: poll the media clock per frame.
  useEffect(() => {
    if (!playing) return;
    const tick = () => {
      const audio = audioRef.current;
      if (audio) setTime(audio.currentTime);
      rafRef.current = requestAnimationFrame(tick);
    };
    rafRef.current = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(rafRef.current);
  }, [playing]);

  const toggle = useCallback(() => {
    const audio = audioRef.current;
    if (!audio) return;
    if (audio.paused) {
      void audio.play();
      setPlaying(true);
    } else {
      audio.pause();
      setPlaying(false);
    }
  }, []);

  const replayLine = useCallback(() => {
    const audio = audioRef.current;
    if (!audio || !doc) return;
    const wi = computeWordIndex(doc, audio.currentTime);
    const seg = doc.segments[Math.max(0, wi.segment)];
    if (seg) {
      audio.currentTime = seg.start;
      setTime(seg.start);
      if (audio.paused) {
        void audio.play();
        setPlaying(true);
      }
    }
  }, [doc]);

  const toggleSlow = useCallback(() => {
    const audio = audioRef.current;
    if (!audio) return;
    const next = !slow;
    audio.playbackRate = next ? 0.8 : 1;
    if ("preservesPitch" in audio) audio.preservesPitch = true;
    setSlow(next);
  }, [slow]);

  const onWordsRead = useCallback((n: number) => {
    setWordsRead((prev) => prev + n);
  }, []);

  // A title with a picture. The manifest says so, because the

  // pipeline that produced it knows and the player should not be

  // guessing from a file extension.

  const isVideo = item?.kind === "video";


  const btn =
    "rounded-lg border border-line bg-surface px-4 py-2.5 text-sm font-medium text-ink transition-colors hover:border-primary disabled:opacity-40";

  return (
    <div className="min-h-screen bg-bg text-ink">
      <header className="mx-auto flex max-w-[860px] items-center justify-between px-4 pt-8 sm:px-6">
        <p className="text-xl font-semibold tracking-tight">
          Every
          <span
            className="rounded-[0.3em] px-[0.15em]"
            style={{ background: "var(--kc-highlight)", color: "var(--kc-highlight-ink)" }}
          >
            Word
          </span>
        </p>
        <nav aria-label="Sections" className="flex flex-wrap items-center gap-x-5 gap-y-2">
          {/*
            The page used to be the reader and nothing else, so none of
            this was reachable: not the TV app, not the agent, not the
            package. Each link is a place somebody else can start using it.
          */}
          <a href="#fire-tv" className="text-sm text-muted transition-colors hover:text-ink">
            Fire TV
          </a>
          <a href="#alexa" className="text-sm text-muted transition-colors hover:text-ink">
            Alexa+
          </a>
          <a href="#developers" className="text-sm text-muted transition-colors hover:text-ink">
            Developers
          </a>
          <button type="button" onClick={cycleTheme} className={btn}>
            Theme: {themeMode}
          </button>
        </nav>
      </header>

      <main className="mx-auto max-w-[860px] px-4 pb-16 sm:px-6">
        {/*
          The hero is the product running, not a description of it. It is
          silent and needs no click, because a demo gated behind audio
          autoplay or a Play button is a demo most visitors never see.
        */}
        <section aria-labelledby="ew-hero-heading" className="mt-8">
          <h1 id="ew-hero-heading" className="sr-only">
            EveryWord: subtitles that light up word by word as they are spoken
          </h1>
          <div className="rounded-2xl border border-line bg-surface p-5 sm:p-7">
            <HeroDemo />
          </div>
          <p className="mt-5 max-w-[680px] text-base leading-relaxed">
            <span className="font-semibold">
              Every video already has subtitles. None of them have words.
            </span>{" "}
            A subtitle file says what was said and when the line starts. It
            never says which word is being spoken, so nothing can highlight
            one. EveryWord adds the only thing missing, to the file a video
            already ships with.
            <InfoButton id="sls" />
          </p>
          <p className="mt-3 max-w-[680px] text-sm leading-relaxed text-muted">
            Below is Sintel, distributed by the Blender Foundation with
            English subtitles inside the file. Those cues are the
            filmmakers&apos;. EveryWord only gave them word timings, and{" "}
            <a className="text-[var(--primary)] underline underline-offset-2" href="#upgrade">
              you can read both files
            </a>
            . Nothing here is a mock-up and nothing here was written by us.
          </p>
          <p className="mt-3 max-w-[680px] text-sm leading-relaxed text-muted">
            This is the technique that ran on Indian national television for
            two decades, reached an estimated 200 million viewers, and has
            been national broadcast policy there since 2019. It worked
            because it rode programmes people had already chosen to watch.
            That only becomes possible for the rest of the world&apos;s video
            when the captions it already has can carry a word.
          </p>
        </section>

        {/*
          The evidence sits directly under the demonstration: a reviewer has
          just watched the claim, so this is the moment it is worth checking.
        */}
        <p className="mt-6 max-w-[640px] rounded-xl border border-line bg-surface p-4 text-sm leading-relaxed">
          <span className="font-semibold">Measured, not promised:</span>{" "}
          against gold-standard word alignments on LibriSpeech (27 speakers,
          788 words we did not record), the highlight lands within{" "}
          <span className="font-semibold">30 ms</span> of the spoken word
          (median)
          <InfoButton id="onset" />, never lights a word early beyond 150 ms
          in 766 matched words
          <InfoButton id="never-early" />, and breaks lines at real pauses 42
          percent of the time where timing-blind chunking manages 2
          <InfoButton id="line-breaks" />. The same run on{" "}
          <span className="font-semibold">test-other</span>, the split
          LibriSpeech itself calls hard, gives the same 30 ms and the same
          zero.{" "}
          <a
            href="https://github.com/usv240/everyword/blob/main/docs/EVAL.md"
            target="_blank"
            rel="noopener noreferrer"
            className="font-medium text-[var(--primary)] underline underline-offset-2"
          >
            Method and full results
          </a>
        </p>

        {!item || !doc ? (
          <div className="mt-12 rounded-2xl border border-line bg-surface p-10 text-center text-muted">
            Loading the story...
          </div>
        ) : (
          <>
            {/* The library: one card per story, keyboard reachable. */}
            <section className="mt-8">
              <h2 className="text-sm font-semibold uppercase tracking-wider text-muted">
                Choose a story
              </h2>
              <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
                {library.map((s) => {
                  const active = s.slug === item.slug;
                  return (
                    <button
                      key={s.slug}
                      type="button"
                      onClick={() => void chooseStory(s)}
                      aria-pressed={active}
                      className={`rounded-xl border p-4 text-left transition-colors ${
                        active
                          ? "border-[var(--primary)] bg-surface"
                          : "border-line bg-surface hover:border-[var(--primary)]"
                      }`}
                    >
                      {/*
                        A video gets a still from itself. A shelf of
                        identical grey rectangles gives a visitor nothing
                        to choose between, and the one title that is a
                        film is the one worth opening first.
                      */}
                      {s.kind === "video" ? (
                        <img
                          src={`/content/${s.slug}.poster.jpg`}
                          alt=""
                          width={640}
                          height={273}
                          loading="lazy"
                          className="mb-3 block h-24 w-full rounded-lg object-cover"
                        />
                      ) : (
                        <div
                          aria-hidden
                          className="mb-3 flex h-24 w-full items-center justify-center rounded-lg bg-bg text-3xl"
                          style={{ fontFamily: "var(--font-reading)" }}
                        >
                          <span className="text-muted">{s.title.replace(/^The /, "").charAt(0)}</span>
                        </div>
                      )}
                      <p className="font-medium text-ink">{s.title}</p>
                      <p className="mt-1 text-xs text-muted">
                        {s.words} words · {Math.floor(s.durationSec / 60)}m{" "}
                        {s.durationSec % 60}s
                      </p>
                      <p className="mt-1 text-[11px] uppercase tracking-wide text-muted">
                        {s.source === "aligned"
                          ? "Film's own subtitles, upgraded"
                          : s.source === "polly"
                            ? "Polly speech marks"
                            : "Transcribe"}
                      </p>
                    </button>
                  );
                })}
              </div>
              <p className="mt-3 text-xs leading-relaxed text-muted">
                Three ways in, one caption format. A video that already
                has subtitles keeps them, and EveryWord adds only the word
                timings. A human recording with no captions is timed by
                Amazon Transcribe (30 ms median, measured). Text with no
                recording at all is read by Amazon Polly, whose speech
                marks carry the words themselves. The first path is the one
                that scales, because it needs nothing that does not already
                exist.
              </p>
            </section>

            <section className="mt-6 rounded-2xl border border-line bg-surface p-6 shadow-sm sm:p-10">
              <div className="flex flex-wrap items-baseline justify-between gap-2">
                {/* The page has one h1, the product itself. A story
                    title is a section inside it, not a second page title. */}
                <h2 className="text-lg font-semibold">{item.title}</h2>
                <p className="text-xs text-muted">
                  {item.words} words · {Math.floor(item.durationSec / 60)}m{" "}
                  {item.durationSec % 60}s
                </p>
              </div>

              {/*
                With a picture, the captions belong on the picture.
                That is where a viewer already looks for subtitles, and
                the entire premise is that this happens during watching
                rather than instead of it. Putting them in a panel below
                would make it a reading exercise with a video attached,
                which is the thing this product is not.
              */}
              {isVideo ? (
                <figure className="relative mt-6 overflow-hidden rounded-xl bg-black">
                  <video
                    ref={audioRef}
                    src={`/content/${item.media}`}
                    className="block h-auto w-full"
                    preload="auto"
                    playsInline
                    onLoadedMetadata={(e) => setDuration(e.currentTarget.duration)}
                    onEnded={() => setPlaying(false)}
                  />
                  <div
                    className="pointer-events-none absolute inset-x-0 bottom-0 flex min-h-[4.5rem] items-end justify-center px-4 pb-4 text-balance text-center sm:pb-6"
                    style={{
                      fontFamily: "var(--font-reading)",
                      fontSize: FONT_SIZES[fontIdx],
                      fontWeight: 600,
                    }}
                  >
                    <span className="rounded-lg bg-black/70 px-3 py-1.5 leading-snug text-white">
                      <KaraokeCaptions doc={doc} time={time} onWordsRead={onWordsRead} />
                    </span>
                  </div>
                </figure>
              ) : (
                <div
                  className="mt-8 flex min-h-[9rem] items-center justify-center text-balance text-center"
                  style={{
                    fontFamily: "var(--font-reading)",
                    fontSize: FONT_SIZES[fontIdx],
                    fontWeight: 500,
                  }}
                >
                  <KaraokeCaptions doc={doc} time={time} onWordsRead={onWordsRead} />
                </div>
              )}

              <input
                type="range"
                aria-label="Position in the story"
                className="mt-8 w-full accent-[var(--primary)]"
                min={0}
                max={duration || item.durationSec}
                step={0.1}
                value={time}
                onChange={(e) => {
                  const t = Number(e.target.value);
                  if (audioRef.current) audioRef.current.currentTime = t;
                  setTime(t);
                }}
              />

              <div className="mt-4 flex flex-wrap items-center gap-2">
                <button
                  type="button"
                  onClick={toggle}
                  className="rounded-lg bg-[var(--primary)] px-6 py-2.5 text-sm font-medium text-[var(--primary-contrast)] transition-opacity hover:opacity-90"
                >
                  {playing ? "Pause" : "Play"}
                </button>
                <button type="button" onClick={replayLine} className={btn}>
                  Read that line again
                </button>
                <button type="button" onClick={toggleSlow} className={btn} aria-pressed={slow}>
                  {slow ? "Normal speed" : "Slow down"}
                </button>
                <button
                  type="button"
                  onClick={() => setFontIdx((i) => (i + 1) % FONT_SIZES.length)}
                  className={btn}
                  aria-label={`Text size, currently ${FONT_LABELS[fontIdx]}. Press to cycle.`}
                >
                  {/*
                    A control that cycles has to say where it is. This
                    read "Text size" in all three states, so a reader who
                    needed a larger size had no way to know whether they
                    had already reached the largest one.
                  */}
                  Text size: {FONT_LABELS[fontIdx]}
                </button>
                <p className="ml-auto text-sm text-muted">
                  Words read along in this story:{" "}
                  <span className="font-semibold text-ink">{wordsRead}</span>
                  <span className="text-muted"> of {countWords(doc)}</span>
                </p>
              </div>

              {/*
                The audio-only titles keep the same element, hidden, so
                there is exactly one <video> mounted and exactly one
                clock. <video> plays an audio file perfectly well, and
                two elements would mean two code paths for play, seek,
                rate and position, plus a drift bug between them.
              */}
              {!isVideo && (
                <video
                  ref={audioRef}
                  src={`/content/${item.media}`}
                  preload="auto"
                  playsInline
                  className="hidden"
                  onLoadedMetadata={(e) => setDuration(e.currentTarget.duration)}
                  onEnded={() => setPlaying(false)}
                />
              )}
            </section>

            <p className="mt-6 text-xs leading-relaxed text-muted">
              {item.attribution} Captions generated with Amazon Transcribe
              word-level timestamps and normalized by @everyword/captions-core
              (42-character lines, clause-aware breaks, gap tiling). This page
              uses the same karaoke-captions-react renderer as the EveryWord
              Fire TV app.
            </p>
          </>
        )}

        {/* What / Why / How, for a first-time reader */}
        <section className="mt-10 grid gap-4 md:grid-cols-3">
          <div className="rounded-2xl border border-line bg-surface p-6">
            <p className="text-xs font-semibold uppercase tracking-wider text-[var(--primary)]">
              What it is
            </p>
            <p className="mt-2 text-sm leading-relaxed text-muted">
              A way to give any video&apos;s existing subtitle track word
              timings, so the word being spoken can be lit as it is spoken.
              Point it at a film and the captions it already has, and it
              returns the same words with a time on each. You just watched
              it work on a real film; the same renderer runs on the
              EveryWord Fire TV app.
            </p>
          </div>
          <div className="rounded-2xl border border-line bg-surface p-6">
            <p className="text-xs font-semibold uppercase tracking-wider text-[var(--primary)]">
              Why it exists
            </p>
            <p className="mt-2 text-sm leading-relaxed text-muted">
              130 million US adults read below a 6th grade level, and
              their children are far more likely to struggle too. In
              India, word-synced subtitles on ordinary television reached
              an estimated 200 million viewers over two decades, and a
              five-year study measured 32 points more children becoming
              good readers. It worked because nobody signed up for it:
              the reading practice rode programmes they had already
              chosen. Amazon proved the same mechanic for books with
              Immersion Reading. No television platform has shipped it
              for video, because until the captions can carry a word,
              there is nothing to light.
            </p>
          </div>
          <div className="rounded-2xl border border-line bg-surface p-6">
            <p className="text-xs font-semibold uppercase tracking-wider text-[var(--primary)]">
              How it works
            </p>
            <p className="mt-2 text-sm leading-relaxed text-muted">
              The subtitle file supplies the words. Amazon Transcribe
              supplies the timings. The recogniser is never asked what
              the words are, so one that hears &ldquo;their&rdquo; for
              &ldquo;there&rdquo; cannot put the wrong spelling in front
              of a child: zero word error by construction. The line
              breaks stay the subtitle author&apos;s, because a human
              chose them. Then the renderer lights the word being spoken
              and your eyes follow it whether you mean to or not. That is
              the whole trick, and it is measured: median 30 ms from
              voice to highlight, never early.
            </p>
          </div>
        </section>

        <section className="mt-10 rounded-2xl border border-line bg-surface p-6 sm:p-8">
          <h2 className="text-sm font-semibold uppercase tracking-wider text-[var(--primary)]">
            The evidence
          </h2>
          <p className="mt-2 text-sm leading-relaxed text-muted">
            EveryWord implements an intervention that other people have
            already measured at national scale. Every figure on this page
            is sourced below, and the full list with our own corrections
            is in the repository.
          </p>
          <ul className="mt-5 space-y-4">
            {EVIDENCE.map((item) => (
              <li key={item.url} className="border-l-2 border-line pl-4">
                <p className="text-sm leading-relaxed">{item.finding}</p>
                <a
                  className="mt-1 inline-block text-xs text-[var(--primary)] underline underline-offset-2"
                  href={item.url}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  {item.source}
                </a>
              </li>
            ))}
          </ul>
          <p className="mt-5 text-xs leading-relaxed text-muted">
            <a
              className="text-[var(--primary)] underline underline-offset-2"
              href="https://github.com/usv240/everyword/blob/main/docs/EVIDENCE.md"
              target="_blank"
              rel="noopener noreferrer"
            >
              Full evidence file
            </a>
            {" · "}
            <a
              className="text-[var(--primary)] underline underline-offset-2"
              href="https://github.com/usv240/everyword/blob/main/docs/EVAL.md"
              target="_blank"
              rel="noopener noreferrer"
            >
              Our measured timing accuracy
            </a>
            {" · "}
            <a
              className="text-[var(--primary)] underline underline-offset-2"
              href="https://github.com/usv240/everyword"
              target="_blank"
              rel="noopener noreferrer"
            >
              Open source (MIT)
            </a>
          </p>
        </section>

        <section id="upgrade" aria-labelledby="ew-upgrade-heading" className="mt-16 scroll-mt-8">
          <h2 id="ew-upgrade-heading" className="text-2xl font-semibold tracking-tight text-ink">
            Every video already has subtitles. None of them have words.
          </h2>
          <p className="mt-3 max-w-[760px] leading-relaxed text-muted">
            That is the gap, and it is why nobody has shipped this for
            video. A subtitle file says what was said and when the line
            starts. It never says which word is being spoken, so nothing
            can highlight one. EveryWord takes the file a video already
            has and adds the only thing missing.
          </p>
          <div className="mt-6">
            <UpgradeProof />
          </div>
        </section>

        <section id="fire-tv" aria-labelledby="ew-firetv-heading" className="mt-16 scroll-mt-8">
          <h2 id="ew-firetv-heading" className="text-2xl font-semibold tracking-tight text-ink">
            On your Fire TV
          </h2>
          <div className="mt-6">
            <FireTv />
          </div>
        </section>

        <section id="alexa" aria-labelledby="ew-alexa-heading" className="mt-16 scroll-mt-8">
          <h2 id="ew-alexa-heading" className="text-2xl font-semibold tracking-tight text-ink">
            Ask Alexa+ for a story
          </h2>
          <p className="mt-3 max-w-[680px] leading-relaxed text-muted">
            An assistant can choose a story that fits a bedtime, skip what a
            child has already finished, explain a word they tripped on, and
            record how far they read. It does all of that through six tools
            on EveryWord&apos;s MCP server, which you can talk to from here.
          </p>
          <div className="mt-6">
            <McpProof />
          </div>
        </section>

        <section id="privacy" aria-labelledby="ew-privacy-heading" className="mt-16 scroll-mt-8">
          <h2 id="ew-privacy-heading" className="text-2xl font-semibold tracking-tight text-ink">
            What EveryWord knows about your child
          </h2>
          <p className="mt-3 max-w-[680px] leading-relaxed text-muted">
            Five fields, and no microphone. This is the section a parent
            reads first, so it is the short one.
          </p>
          <div className="mt-6">
            <Privacy />
          </div>
        </section>

        <section id="faq" aria-labelledby="ew-faq-heading" className="mt-16 scroll-mt-8">
          <h2 id="ew-faq-heading" className="text-2xl font-semibold tracking-tight text-ink">
            The questions a parent asks
          </h2>
          <div className="mt-6">
            <Faq />
          </div>
        </section>

        <section id="developers" aria-labelledby="ew-dev-heading" className="mt-16 scroll-mt-8">
          <h2 id="ew-dev-heading" className="text-2xl font-semibold tracking-tight text-ink">
            For developers
          </h2>
          <div className="mt-6">
            <Developers />
          </div>
        </section>
      </main>
    </div>
  );
}
