"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import type { CaptionDoc } from "@everyword/captions-core";
import { computeWordIndex, countWords } from "@everyword/captions-core";
import { KaraokeCaptions } from "karaoke-captions-react";

/**
 * The EveryWord reader.
 *
 * Real public-domain content, real word-timed captions generated by the
 * EveryWord pipeline (Amazon Transcribe), rendered karaoke style: words
 * light up as they are spoken, and watching quietly becomes reading.
 * This page is the same renderer the Fire TV app uses.
 */

interface ManifestItem {
  slug: string;
  title: string;
  attribution: string;
  media: string;
  captions: string;
  words: number;
  durationSec: number;
  source?: "polly" | "transcribe";
}

const FONT_SIZES = ["1.6rem", "2.1rem", "2.7rem"];

function useTheme(): [string, () => void] {
  const [mode, setMode] = useState("system");
  useEffect(() => {
    try {
      const t = localStorage.getItem("ew-theme");
      if (t === "light" || t === "dark") setMode(t);
    } catch {
      /* storage unavailable */
    }
  }, []);
  const cycle = useCallback(() => {
    setMode((prev) => {
      const next = prev === "system" ? "light" : prev === "light" ? "dark" : "system";
      const root = document.documentElement;
      if (next === "system") root.removeAttribute("data-theme");
      else root.setAttribute("data-theme", next);
      try {
        if (next === "system") localStorage.removeItem("ew-theme");
        else localStorage.setItem("ew-theme", next);
      } catch {
        /* ignore */
      }
      return next;
    });
  }, []);
  return [mode, cycle];
}

export default function Reader() {
  const [library, setLibrary] = useState<ManifestItem[]>([]);
  const [item, setItem] = useState<ManifestItem | null>(null);
  const [doc, setDoc] = useState<CaptionDoc | null>(null);
  const [time, setTime] = useState(0);
  const [playing, setPlaying] = useState(false);
  const [slow, setSlow] = useState(false);
  const [fontIdx, setFontIdx] = useState(1);
  const [wordsRead, setWordsRead] = useState(0);
  const [duration, setDuration] = useState(0);
  const audioRef = useRef<HTMLAudioElement>(null);
  const rafRef = useRef(0);
  const [themeMode, cycleTheme] = useTheme();

  useEffect(() => {
    (async () => {
      const manifest = (await fetch("/content/manifest.json").then((r) => r.json())) as {
        items: ManifestItem[];
      };
      if (!manifest.items.length) return;
      setLibrary(manifest.items);
      const first = manifest.items[0]!;
      setItem(first);
      const captions = (await fetch(`/content/${first.captions}`).then((r) =>
        r.json(),
      )) as CaptionDoc;
      setDoc(captions);
    })().catch(() => setItem(null));
  }, []);

  /** Switching stories resets playback and the per-story reading meter. */
  const chooseStory = useCallback(
    async (next: ManifestItem) => {
      if (next.slug === item?.slug) return;
      const audio = audioRef.current;
      if (audio) audio.pause();
      setPlaying(false);
      setTime(0);
      setWordsRead(0);
      setDuration(0);
      setItem(next);
      const captions = (await fetch(`/content/${next.captions}`).then((r) =>
        r.json(),
      )) as CaptionDoc;
      setDoc(captions);
    },
    [item?.slug],
  );

  // Smooth time updates while playing: poll the media clock per frame.
  useEffect(() => {
    if (!playing) return;
    const tick = () => {
      const audio = audioRef.current;
      if (audio) setTime(audio.currentTime);
      rafRef.current = requestAnimationFrame(tick);
    };
    rafRef.current = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(rafRef.current);
  }, [playing]);

  const toggle = useCallback(() => {
    const audio = audioRef.current;
    if (!audio) return;
    if (audio.paused) {
      void audio.play();
      setPlaying(true);
    } else {
      audio.pause();
      setPlaying(false);
    }
  }, []);

  const replayLine = useCallback(() => {
    const audio = audioRef.current;
    if (!audio || !doc) return;
    const wi = computeWordIndex(doc, audio.currentTime);
    const seg = doc.segments[Math.max(0, wi.segment)];
    if (seg) {
      audio.currentTime = seg.start;
      setTime(seg.start);
      if (audio.paused) {
        void audio.play();
        setPlaying(true);
      }
    }
  }, [doc]);

  const toggleSlow = useCallback(() => {
    const audio = audioRef.current;
    if (!audio) return;
    const next = !slow;
    audio.playbackRate = next ? 0.8 : 1;
    if ("preservesPitch" in audio) audio.preservesPitch = true;
    setSlow(next);
  }, [slow]);

  const onWordsRead = useCallback((n: number) => {
    setWordsRead((prev) => prev + n);
  }, []);

  const btn =
    "rounded-lg border border-line bg-surface px-4 py-2.5 text-sm font-medium text-ink transition-colors hover:border-primary disabled:opacity-40";

  return (
    <div className="min-h-screen bg-bg text-ink">
      <header className="mx-auto flex max-w-[860px] items-center justify-between px-4 pt-8 sm:px-6">
        <p className="text-xl font-semibold tracking-tight">
          Every
          <span
            className="rounded-[0.3em] px-[0.15em]"
            style={{ background: "var(--kc-highlight)", color: "var(--kc-highlight-ink)" }}
          >
            Word
          </span>
        </p>
        <button type="button" onClick={cycleTheme} className={btn}>
          Theme: {themeMode}
        </button>
      </header>

      <main className="mx-auto max-w-[860px] px-4 pb-16 sm:px-6">
        <p className="mt-6 max-w-[620px] text-sm leading-relaxed text-muted">
          Subtitles that light up word by word as they are spoken. The same
          technique that has given reading practice to 200 million people in
          India, running here on a real public-domain story with captions
          generated by the EveryWord pipeline on Amazon Transcribe.
        </p>
        <p className="mt-4 max-w-[620px] rounded-xl border border-line bg-surface p-4 text-sm leading-relaxed">
          <span className="font-semibold">Measured, not promised:</span>{" "}
          against gold-standard word alignments on LibriSpeech (27 speakers,
          788 words we did not record), the highlight lands within{" "}
          <span className="font-semibold">30 ms</span> of the spoken word
          (median), never lights a word early beyond 150 ms in 766 matched
          words, and breaks lines at real pauses 42 percent of the time where
          timing-blind chunking manages 2.{" "}
          <a
            href="https://github.com/usv240/everyword/blob/main/docs/EVAL.md"
            target="_blank"
            rel="noopener noreferrer"
            className="font-medium text-[var(--primary)] underline underline-offset-2"
          >
            Method and full results
          </a>
        </p>

        {!item || !doc ? (
          <div className="mt-12 rounded-2xl border border-line bg-surface p-10 text-center text-muted">
            Loading the story...
          </div>
        ) : (
          <>
            {/* The library: one card per story, keyboard reachable. */}
            <section className="mt-8">
              <h2 className="text-sm font-semibold uppercase tracking-wider text-muted">
                Choose a story
              </h2>
              <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
                {library.map((s) => {
                  const active = s.slug === item.slug;
                  return (
                    <button
                      key={s.slug}
                      type="button"
                      onClick={() => void chooseStory(s)}
                      aria-pressed={active}
                      className={`rounded-xl border p-4 text-left transition-colors ${
                        active
                          ? "border-[var(--primary)] bg-surface"
                          : "border-line bg-surface hover:border-[var(--primary)]"
                      }`}
                    >
                      <p className="font-medium text-ink">{s.title}</p>
                      <p className="mt-1 text-xs text-muted">
                        {s.words} words · {Math.floor(s.durationSec / 60)}m{" "}
                        {s.durationSec % 60}s ·{" "}
                        {s.source === "polly" ? "Polly speech marks" : "Transcribe"}
                      </p>
                    </button>
                  );
                })}
              </div>
              <p className="mt-3 text-xs leading-relaxed text-muted">
                Two pipelines, one caption format. Stories read by a human are
                timed with Amazon Transcribe (30 ms median accuracy, measured).
                Stories synthesized from public-domain text are timed from
                Amazon Polly speech marks, which carry the words themselves, so
                those captions have zero word error by construction. Any book
                ever written can become a read-along this way.
              </p>
            </section>

            <section className="mt-6 rounded-2xl border border-line bg-surface p-6 shadow-sm sm:p-10">
              <div className="flex flex-wrap items-baseline justify-between gap-2">
                <h1 className="text-lg font-semibold">{item.title}</h1>
                <p className="text-xs text-muted">
                  {item.words} words · {Math.floor(item.durationSec / 60)}m{" "}
                  {item.durationSec % 60}s
                </p>
              </div>

              <div
                className="mt-8 flex min-h-[9rem] items-center justify-center text-balance text-center"
                style={{
                  fontFamily: "var(--font-reading)",
                  fontSize: FONT_SIZES[fontIdx],
                  fontWeight: 500,
                }}
              >
                <KaraokeCaptions doc={doc} time={time} onWordsRead={onWordsRead} />
              </div>

              <input
                type="range"
                aria-label="Position in the story"
                className="mt-8 w-full accent-[var(--primary)]"
                min={0}
                max={duration || item.durationSec}
                step={0.1}
                value={time}
                onChange={(e) => {
                  const t = Number(e.target.value);
                  if (audioRef.current) audioRef.current.currentTime = t;
                  setTime(t);
                }}
              />

              <div className="mt-4 flex flex-wrap items-center gap-2">
                <button
                  type="button"
                  onClick={toggle}
                  className="rounded-lg bg-[var(--primary)] px-6 py-2.5 text-sm font-medium text-[var(--primary-contrast)] transition-opacity hover:opacity-90"
                >
                  {playing ? "Pause" : "Play"}
                </button>
                <button type="button" onClick={replayLine} className={btn}>
                  Read that line again
                </button>
                <button type="button" onClick={toggleSlow} className={btn} aria-pressed={slow}>
                  {slow ? "Normal speed" : "Slow down"}
                </button>
                <button
                  type="button"
                  onClick={() => setFontIdx((i) => (i + 1) % FONT_SIZES.length)}
                  className={btn}
                >
                  Text size
                </button>
                <p className="ml-auto text-sm text-muted">
                  Words read along in this story:{" "}
                  <span className="font-semibold text-ink">{wordsRead}</span>
                  <span className="text-muted"> of {countWords(doc)}</span>
                </p>
              </div>

              <audio
                ref={audioRef}
                src={`/content/${item.media}`}
                preload="auto"
                onLoadedMetadata={(e) => setDuration(e.currentTarget.duration)}
                onEnded={() => setPlaying(false)}
              />
            </section>

            <p className="mt-6 text-xs leading-relaxed text-muted">
              {item.attribution} Captions generated with Amazon Transcribe
              word-level timestamps and normalized by @everyword/captions-core
              (42-character lines, clause-aware breaks, gap tiling). This page
              uses the same karaoke-captions-react renderer as the EveryWord
              Fire TV app.
            </p>

            {/* What / Why / How, for a first-time reader */}
            <section className="mt-10 grid gap-4 md:grid-cols-3">
              <div className="rounded-2xl border border-line bg-surface p-6">
                <p className="text-xs font-semibold uppercase tracking-wider text-[var(--primary)]">
                  What it is
                </p>
                <p className="mt-2 text-sm leading-relaxed text-muted">
                  Subtitles that light up word by word, exactly as each word is
                  spoken, on any video or audio. You just watched it work; the
                  same renderer runs on the EveryWord Fire TV app.
                </p>
              </div>
              <div className="rounded-2xl border border-line bg-surface p-6">
                <p className="text-xs font-semibold uppercase tracking-wider text-[var(--primary)]">
                  Why it exists
                </p>
                <p className="mt-2 text-sm leading-relaxed text-muted">
                  130 million US adults read below a 6th grade level, and their
                  children are far more likely to struggle too. Word-synced
                  subtitles on ordinary TV gave measurable reading practice to
                  200 million people in India over two decades. No TV platform
                  has ever shipped it. Amazon already proved the mechanic for
                  books with Immersion Reading; this is Immersion Reading for
                  television.
                </p>
              </div>
              <div className="rounded-2xl border border-line bg-surface p-6">
                <p className="text-xs font-semibold uppercase tracking-wider text-[var(--primary)]">
                  How it works
                </p>
                <p className="mt-2 text-sm leading-relaxed text-muted">
                  Amazon Transcribe times every word. Our open caption engine
                  breaks the words into readable 42-character lines at clauses
                  and real pauses, and tiles tiny gaps so the highlight never
                  flickers. The renderer lights the word being spoken; your
                  eyes follow it whether you mean to or not. That is the whole
                  trick, and it is measured: median 30 ms from voice to
                  highlight, never early.
                </p>
              </div>
            </section>

            <p className="mt-6 text-xs leading-relaxed text-muted">
              Evidence:{" "}
              <a
                className="text-[var(--primary)] underline underline-offset-2"
                href="https://www.uil.unesco.org/en/litbase/reading-billion-same-language-subtitling-india"
                target="_blank"
                rel="noopener noreferrer"
              >
                UNESCO on Same Language Subtitling in India
              </a>
              {" · "}
              <a
                className="text-[var(--primary)] underline underline-offset-2"
                href="https://pmc.ncbi.nlm.nih.gov/articles/PMC5214590/"
                target="_blank"
                rel="noopener noreferrer"
              >
                100+ studies: captions improve reading
              </a>
              {" · "}
              <a
                className="text-[var(--primary)] underline underline-offset-2"
                href="https://github.com/usv240/everyword/blob/main/docs/EVAL.md"
                target="_blank"
                rel="noopener noreferrer"
              >
                our measured timing accuracy
              </a>
              {" · "}
              <a
                className="text-[var(--primary)] underline underline-offset-2"
                href="https://github.com/usv240/everyword"
                target="_blank"
                rel="noopener noreferrer"
              >
                open source (MIT)
              </a>
            </p>
          </>
        )}
      </main>
    </div>
  );
}
