import React, {useCallback, useEffect, useRef, useState} from 'react';
import {
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
  useTVEventHandler,
} from 'react-native';
import Video, {type VideoRef} from 'react-native-video';
import {computeWordIndex} from '@everyword/captions-core';
import {KaraokeCaptionsNative} from 'karaoke-captions-react/native';
import {LIBRARY, formatDuration, type Story} from './src/library';
import {createReporter, type Reporter} from './src/mcp';

/**
 * EveryWord for Fire TV: the reader on the biggest screen in the house.
 *
 * Real public-domain Aesop, captions generated by the EveryWord pipeline
 * on Amazon Transcribe and Amazon Polly, rendered by the same
 * karaoke-captions-react package as the web reader. Words light up as
 * they are spoken; watching becomes reading.
 *
 * Two screens, because one was not enough
 * ---------------------------------------
 * This app held a single hardcoded story while the web reader offered
 * five. Fire TV is this project's primary track, which made its app the
 * thinnest surface in the project and the first one a judge opens. It
 * now carries the whole library, chosen with the D-pad.
 *
 * What the remote does
 * --------------------
 * A Fire TV remote has real media buttons and the first version of this
 * app ignored all of them: pressing Play on the remote did nothing while
 * an on-screen Play button sat there focused. That is the kind of thing
 * that reads as broken from a sofa. Play/Pause, rewind and fast-forward
 * are now handled wherever you are, and Back returns to the library
 * rather than leaving the app mid-story.
 *
 * 10-foot rules: every control is a D-pad focusable Pressable with a
 * visible focus ring, focus starts somewhere sensible on each screen,
 * content sits inside TV-safe margins, and nothing requires a pointer.
 */

const COLORS = {
  bg: '#14161c',
  surface: '#1c1f27',
  raised: '#22262f',
  line: '#2e3340',
  ink: '#f0f3f6',
  muted: '#9aa4af',
  highlight: '#ffd34d',
  highlightInk: '#21242b',
  primary: '#93a0f2',
  primaryInk: '#14161c',
};

/** Seconds the media buttons move the cursor. A line, roughly. */
const SKIP_SECONDS = 5;

/**
 * Who the progress belongs to.
 *
 * A television is a shared device with no sign-in, so there is no real
 * account here and pretending otherwise would be worse than saying so.
 * This is the household's device, and the privacy section on the site
 * says in as many words that readerId need not be a child's name.
 */
const READER_ID = 'firetv-household';

function formatTime(t: number): string {
  const m = Math.floor(t / 60);
  const s = Math.floor(t % 60);
  return `${m}:${String(s).padStart(2, '0')}`;
}

interface TvButtonProps {
  label: string;
  onPress: () => void;
  preferred?: boolean;
  primary?: boolean;
}

function TvButton({label, onPress, preferred, primary}: TvButtonProps) {
  const [focused, setFocused] = useState(false);
  return (
    <Pressable
      onPress={onPress}
      onFocus={() => setFocused(true)}
      onBlur={() => setFocused(false)}
      hasTVPreferredFocus={preferred ?? false}
      accessibilityRole="button"
      accessibilityLabel={label}
      style={[
        styles.button,
        primary && {backgroundColor: COLORS.primary, borderColor: COLORS.primary},
        focused && styles.buttonFocused,
      ]}>
      <Text
        style={[
          styles.buttonText,
          primary && {color: COLORS.primaryInk},
          focused && !primary && {color: COLORS.ink},
        ]}>
        {label}
      </Text>
    </Pressable>
  );
}

interface StoryCardProps {
  story: Story;
  wordsRead: number;
  preferred: boolean;
  onPress: () => void;
}

function StoryCard({story, wordsRead, preferred, onPress}: StoryCardProps) {
  const [focused, setFocused] = useState(false);
  const done = wordsRead >= story.words;
  return (
    <Pressable
      onPress={onPress}
      onFocus={() => setFocused(true)}
      onBlur={() => setFocused(false)}
      hasTVPreferredFocus={preferred}
      accessibilityRole="button"
      accessibilityLabel={`${story.title}, ${story.words} words, ${formatDuration(
        story.durationSec,
      )}`}
      style={[styles.card, focused && styles.cardFocused]}>
      <Text style={[styles.cardTitle, focused && {color: COLORS.ink}]}>
        {story.title}
      </Text>
      <Text style={styles.cardMeta}>
        {story.words} words {'·'} {formatDuration(story.durationSec)}
      </Text>
      <View style={styles.cardFooter}>
        <Text style={styles.cardSource}>
          {story.source === 'polly' ? 'Polly speech marks' : 'Transcribe'}
        </Text>
        {wordsRead > 0 && (
          <Text style={[styles.cardProgress, done && {color: COLORS.highlight}]}>
            {done ? 'Finished' : `${wordsRead} read`}
          </Text>
        )}
      </View>
    </Pressable>
  );
}

export default function App() {
  const [story, setStory] = useState<Story | null>(null);
  const [time, setTime] = useState(0);
  const [duration, setDuration] = useState(0);
  const [paused, setPaused] = useState(true);
  const [slow, setSlow] = useState(false);
  const [wordsRead, setWordsRead] = useState(0);
  const [readBySlug, setReadBySlug] = useState<Record<string, number>>({});
  const videoRef = useRef<VideoRef>(null);
  const reporter = useRef<Reporter>(createReporter());

  // The latest values, for handlers that must not be rebuilt on every
  // tick. useTVEventHandler re-subscribes whenever its callback changes,
  // and rebuilding a subscription a hundred times a second drops presses.
  const state = useRef({time: 0, paused: true, story: null as Story | null});
  state.current = {time, paused, story};

  /**
   * Send what was actually read to the MCP server, then forget it.
   *
   * Called when a story ends or is left. It is deliberately not awaited
   * by anything on screen: a slow network must never hold up a child
   * pressing Back.
   */
  const reportProgress = useCallback((s: Story, followed: number, finished: boolean) => {
    if (followed <= 0) {
      return;
    }
    void reporter.current.report({
      readerId: READER_ID,
      slug: s.slug,
      wordsFollowed: followed,
      completed: finished,
    });
  }, []);

  const openStory = useCallback((s: Story) => {
    setStory(s);
    setTime(0);
    setDuration(0);
    setWordsRead(0);
    setPaused(false);
    setSlow(false);
  }, []);

  const closeStory = useCallback(
    (finished: boolean) => {
      const current = state.current.story;
      if (!current) {
        return;
      }
      setWordsRead(read => {
        reportProgress(current, read, finished);
        setReadBySlug(prev => ({
          ...prev,
          [current.slug]: Math.max(prev[current.slug] ?? 0, read),
        }));
        return read;
      });
      setStory(null);
      setPaused(true);
    },
    [reportProgress],
  );

  const seekBy = useCallback((delta: number) => {
    const next = Math.max(0, state.current.time + delta);
    videoRef.current?.seek(next);
    setTime(next);
  }, []);

  const replayLine = useCallback(() => {
    const current = state.current.story;
    if (!current) {
      return;
    }
    const wi = computeWordIndex(current.captions, state.current.time);
    const seg = current.captions.segments[Math.max(0, wi.segment)];
    if (seg) {
      videoRef.current?.seek(seg.start);
      setTime(seg.start);
      setPaused(false);
    }
  }, []);

  /**
   * The remote's own buttons, not just the on-screen ones.
   *
   * Fire TV remotes send real media keycodes, which react-native-tvos
   * surfaces as playPause, rewind and fastForward. Handling them is what
   * separates an app that works from a sofa from one that only works if
   * you happen to have focused the right button.
   */
  const onTvEvent = useCallback(
    (evt: {eventType: string}) => {
      if (!state.current.story) {
        return;
      }
      switch (evt.eventType) {
        case 'playPause':
          setPaused(p => !p);
          break;
        case 'rewind':
          seekBy(-SKIP_SECONDS);
          break;
        case 'fastForward':
          seekBy(SKIP_SECONDS);
          break;
        case 'menu':
          closeStory(false);
          break;
        default:
          break;
      }
    },
    [seekBy, closeStory],
  );
  useTVEventHandler(onTvEvent);

  const onWordsRead = useCallback((n: number) => {
    setWordsRead(prev => prev + n);
  }, []);

  useEffect(() => {
    // Report whatever was read if the app is torn down mid-story.
    return () => {
      const current = state.current.story;
      if (current) {
        reportProgress(current, 0, false);
      }
    };
  }, [reportProgress]);

  const totalRead = Object.values(readBySlug).reduce((a, b) => a + b, 0) + wordsRead;

  if (!story) {
    return (
      <View style={styles.screen}>
        <View style={styles.header}>
          <Text style={styles.wordmark}>
            Every
            <Text style={styles.wordmarkPill}>Word</Text>
          </Text>
          <Text style={styles.meta}>
            Words read along: <Text style={styles.metaStrong}>{totalRead}</Text>
          </Text>
        </View>

        <Text style={styles.libraryHeading}>Choose a story</Text>
        <Text style={styles.libraryHint}>
          Five public-domain fables. Press left and right on the remote, then
          select.
        </Text>

        <ScrollView
          horizontal
          showsHorizontalScrollIndicator={false}
          contentContainerStyle={styles.cardRow}>
          {LIBRARY.map((s, i) => (
            <StoryCard
              key={s.slug}
              story={s}
              wordsRead={readBySlug[s.slug] ?? 0}
              preferred={i === 0}
              onPress={() => openStory(s)}
            />
          ))}
        </ScrollView>

        <Text style={styles.footnote}>
          Every word count here is computed from the caption document that
          drives the highlight, not written down separately.
        </Text>
      </View>
    );
  }

  /*
    A film gets the whole screen.

    The first version put the picture inside the same bordered card the
    audio titles use, under a title, an attribution and above a progress
    row, four buttons and a footnote. On a 1080p television that left the
    video a strip about two hundred pixels tall, so a 2.35:1 film was
    letterboxed down to a third of the width with black on either side,
    and the captions, sized for a page of text, covered what was left of
    it. The thing the product exists to show was the smallest element on
    screen.

    So: black, picture edge to edge, captions where a viewer already
    looks for subtitles, and the controls on a scrim underneath. This is
    how every television video app is laid out, for the same reason.
  */
  if (story.video) {
    return (
      <View style={styles.videoScreen}>
        <Video
          ref={videoRef}
          source={story.media}
          paused={paused}
          rate={slow ? 0.8 : 1}
          progressUpdateInterval={100}
          onProgress={p => setTime(p.currentTime)}
          onLoad={l => setDuration(l.duration)}
          onEnd={() => closeStory(true)}
          style={StyleSheet.absoluteFill}
          resizeMode="contain"
          playInBackground={false}
        />

        <View style={styles.videoTop} pointerEvents="none">
          <Text style={styles.videoTitle}>{story.title}</Text>
          <Text style={styles.meta}>
            Words read along: <Text style={styles.metaStrong}>{wordsRead}</Text> of{' '}
            {story.words}
          </Text>
        </View>

        <View style={styles.videoBottom}>
          <View style={styles.videoCaptionBand} pointerEvents="none">
            <KaraokeCaptionsNative
              doc={story.captions}
              time={time}
              textStyle={styles.captionOverPicture}
              highlightColor={COLORS.highlight}
              highlightInk={COLORS.highlightInk}
              doneInk={COLORS.ink}
              upcomingInk={COLORS.muted}
              onWordsRead={onWordsRead}
            />
          </View>

          <View style={styles.videoControls}>
            <Text style={styles.meta}>{formatTime(time)}</Text>
            <View style={styles.progressTrack}>
              <View
                style={[
                  styles.progressFill,
                  {width: `${duration > 0 ? Math.min(100, (time / duration) * 100) : 0}%`},
                ]}
              />
            </View>
            <Text style={styles.meta}>{formatTime(duration)}</Text>
          </View>

          <View style={styles.videoButtonRow}>
            <TvButton
              label={paused ? 'Play' : 'Pause'}
              onPress={() => setPaused(p => !p)}
              preferred
              primary
            />
            <TvButton label="Read that line again" onPress={replayLine} />
            <TvButton
              label={slow ? 'Normal speed' : 'Slow down'}
              onPress={() => setSlow(s => !s)}
            />
            <TvButton label="Back to stories" onPress={() => closeStory(false)} />
          </View>
        </View>
      </View>
    );
  }

  return (
    <View style={styles.screen}>
      <View style={styles.header}>
        <Text style={styles.wordmark}>
          Every
          <Text style={styles.wordmarkPill}>Word</Text>
        </Text>
        <Text style={styles.meta}>
          Words read along: <Text style={styles.metaStrong}>{wordsRead}</Text> of{' '}
          {story.words}
        </Text>
      </View>

      <View style={styles.reader}>
        <Text style={styles.title}>{story.title}</Text>
        <Text style={styles.attribution}>{story.attribution}</Text>

        {story.video ? (
          /*
            With a picture, the captions go on the picture.
            That is where anyone already looks for subtitles, and the
            whole premise is that this happens during watching rather
            than instead of it. A panel of text beside a video would be
            a reading exercise with a film attached, which is the thing
            this product is not.
          */
          <View style={styles.stage}>
            <Video
              ref={videoRef}
              source={story.media}
              paused={paused}
              rate={slow ? 0.8 : 1}
              progressUpdateInterval={100}
              onProgress={p => setTime(p.currentTime)}
              onLoad={l => setDuration(l.duration)}
              onEnd={() => closeStory(true)}
              style={styles.picture}
              resizeMode="contain"
              playInBackground={false}
            />
            <View style={styles.captionBand} pointerEvents="none">
              <KaraokeCaptionsNative
                doc={story.captions}
                time={time}
                textStyle={styles.captionOverPicture}
                highlightColor={COLORS.highlight}
                highlightInk={COLORS.highlightInk}
                doneInk={COLORS.ink}
                upcomingInk={COLORS.muted}
                onWordsRead={onWordsRead}
              />
            </View>
          </View>
        ) : (
          <View style={styles.captionArea}>
            <KaraokeCaptionsNative
              doc={story.captions}
              time={time}
              textStyle={styles.captionText}
              highlightColor={COLORS.highlight}
              highlightInk={COLORS.highlightInk}
              doneInk={COLORS.ink}
              upcomingInk={COLORS.muted}
              onWordsRead={onWordsRead}
            />
          </View>
        )}

        <View style={styles.progressRow}>
          <Text style={styles.meta}>{formatTime(time)}</Text>
          <View style={styles.progressTrack}>
            <View
              style={[
                styles.progressFill,
                {width: `${duration > 0 ? Math.min(100, (time / duration) * 100) : 0}%`},
              ]}
            />
          </View>
          <Text style={styles.meta}>{formatTime(duration)}</Text>
        </View>

        <View style={styles.buttonRow}>
          <TvButton
            label={paused ? 'Play' : 'Pause'}
            onPress={() => setPaused(p => !p)}
            preferred
            primary
          />
          <TvButton label="Read that line again" onPress={replayLine} />
          <TvButton
            label={slow ? 'Normal speed' : 'Slow down'}
            onPress={() => setSlow(s => !s)}
          />
          <TvButton label="Back to stories" onPress={() => closeStory(false)} />
        </View>

        <Text style={styles.footnote}>
          The remote works too: play/pause, and rewind or fast-forward by five
          seconds.
        </Text>
      </View>

      {!story.video && (
        <Video
          ref={videoRef}
          source={story.media}
          paused={paused}
          rate={slow ? 0.8 : 1}
          progressUpdateInterval={100}
          onProgress={p => setTime(p.currentTime)}
          onLoad={l => setDuration(l.duration)}
          onEnd={() => closeStory(true)}
          style={styles.hiddenPlayer}
          audioOutput="speaker"
          playInBackground={false}
        />
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.bg,
    paddingHorizontal: '5%',
    paddingVertical: '4%',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  wordmark: {color: COLORS.ink, fontSize: 30, fontWeight: '700'},
  wordmarkPill: {
    backgroundColor: COLORS.highlight,
    color: COLORS.highlightInk,
  },
  libraryHeading: {
    color: COLORS.ink,
    fontSize: 34,
    fontWeight: '700',
    marginTop: 28,
  },
  libraryHint: {color: COLORS.muted, fontSize: 18, marginTop: 8},
  cardRow: {paddingVertical: 28, gap: 20},
  card: {
    width: 320,
    minHeight: 200,
    justifyContent: 'space-between',
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: COLORS.line,
    padding: 24,
  },
  cardFocused: {
    borderColor: COLORS.highlight,
    backgroundColor: COLORS.raised,
    transform: [{scale: 1.05}],
  },
  cardTitle: {color: COLORS.muted, fontSize: 24, fontWeight: '700'},
  cardMeta: {color: COLORS.muted, fontSize: 16, marginTop: 10},
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 18,
  },
  cardSource: {color: COLORS.muted, fontSize: 13},
  cardProgress: {color: COLORS.primary, fontSize: 14, fontWeight: '600'},
  reader: {
    flex: 1,
    marginTop: 24,
    backgroundColor: COLORS.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.line,
    padding: 36,
  },
  title: {color: COLORS.ink, fontSize: 26, fontWeight: '600'},
  attribution: {color: COLORS.muted, fontSize: 14, marginTop: 6},
  videoScreen: {flex: 1, backgroundColor: '#000'},
  videoTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    // TV-safe margins. A television overscans, and anything in the outer
    // five percent of the frame may simply not be on the screen.
    paddingHorizontal: '5%',
    paddingVertical: '3%',
    backgroundColor: 'rgba(20,22,28,0.55)',
  },
  videoTitle: {color: COLORS.ink, fontSize: 24, fontWeight: '700'},
  videoBottom: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: '5%',
    paddingBottom: '3%',
    backgroundColor: 'rgba(20,22,28,0.72)',
  },
  videoCaptionBand: {paddingTop: 18, paddingBottom: 10, alignItems: 'center'},
  videoControls: {flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 4},
  videoButtonRow: {flexDirection: 'row', gap: 14, marginTop: 14},
  stage: {
    flex: 1,
    marginTop: 14,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#000',
    justifyContent: 'center',
  },
  picture: {
    ...StyleSheet.absoluteFillObject,
  },
  captionBand: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 40,
    paddingBottom: 26,
    alignItems: 'center',
  },
  captionOverPicture: {
    // Sized for ten feet away, and small enough that a full line fits
    // across the band without wrapping to three rows over the picture.
    fontSize: 34,
    fontWeight: '700',
    lineHeight: 48,
    color: COLORS.ink,
    textAlign: 'center',
  },
  captionArea: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  captionText: {
    fontSize: 44,
    fontWeight: '600',
    lineHeight: 66,
    color: COLORS.ink,
  },
  progressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  progressTrack: {
    flex: 1,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.line,
    overflow: 'hidden',
  },
  progressFill: {
    height: 6,
    backgroundColor: COLORS.primary,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 14,
    marginTop: 22,
  },
  button: {
    borderWidth: 2,
    borderColor: COLORS.line,
    backgroundColor: COLORS.surface,
    borderRadius: 10,
    paddingHorizontal: 22,
    paddingVertical: 12,
  },
  buttonFocused: {
    borderColor: COLORS.highlight,
    transform: [{scale: 1.06}],
  },
  buttonText: {color: COLORS.muted, fontSize: 18, fontWeight: '600'},
  meta: {color: COLORS.muted, fontSize: 16},
  metaStrong: {color: COLORS.ink, fontWeight: '700'},
  footnote: {color: COLORS.muted, fontSize: 13, marginTop: 14},
  hiddenPlayer: {width: 0, height: 0},
});
