import React, {useCallback, useRef, useState} from 'react';
import {Pressable, StyleSheet, Text, View} from 'react-native';
import Video, {type VideoRef} from 'react-native-video';
import {computeWordIndex, countWords, type CaptionDoc} from '@everyword/captions-core';
import {KaraokeCaptionsNative} from 'karaoke-captions-react/src/native';

/**
 * EveryWord for Fire TV: the reader on the biggest screen in the house.
 *
 * Real public-domain content (Aesop's The Two Pots, read by LibriVox
 * volunteers) with captions generated by the EveryWord pipeline on Amazon
 * Transcribe, rendered by the same karaoke-captions-react package as the
 * web reader. Words light up as they are spoken; watching becomes reading.
 *
 * 10-foot rules: every control is a D-pad focusable Pressable with a
 * visible focus ring, Play has preferred focus, text sits inside TV-safe
 * margins, and nothing requires a pointer.
 */

const captions = require('./assets/two-pots.captions.json') as CaptionDoc;
const media = require('./assets/two-pots.mp3');

const COLORS = {
  bg: '#14161c',
  surface: '#1c1f27',
  line: '#2e3340',
  ink: '#f0f3f6',
  muted: '#9aa4af',
  highlight: '#ffd34d',
  highlightInk: '#21242b',
  primary: '#93a0f2',
  primaryInk: '#14161c',
};

function formatTime(t: number): string {
  const m = Math.floor(t / 60);
  const s = Math.floor(t % 60);
  return `${m}:${String(s).padStart(2, '0')}`;
}

interface TvButtonProps {
  label: string;
  onPress: () => void;
  preferred?: boolean;
  primary?: boolean;
}

function TvButton({label, onPress, preferred, primary}: TvButtonProps) {
  const [focused, setFocused] = useState(false);
  return (
    <Pressable
      onPress={onPress}
      onFocus={() => setFocused(true)}
      onBlur={() => setFocused(false)}
      hasTVPreferredFocus={preferred ?? false}
      style={[
        styles.button,
        primary && {backgroundColor: COLORS.primary, borderColor: COLORS.primary},
        focused && styles.buttonFocused,
      ]}>
      <Text
        style={[
          styles.buttonText,
          primary && {color: COLORS.primaryInk},
          focused && !primary && {color: COLORS.ink},
        ]}>
        {label}
      </Text>
    </Pressable>
  );
}

export default function App() {
  const [time, setTime] = useState(0);
  const [duration, setDuration] = useState(0);
  const [paused, setPaused] = useState(true);
  const [slow, setSlow] = useState(false);
  const [wordsRead, setWordsRead] = useState(0);
  const videoRef = useRef<VideoRef>(null);

  const replayLine = useCallback(() => {
    const wi = computeWordIndex(captions, time);
    const seg = captions.segments[Math.max(0, wi.segment)];
    if (seg) {
      videoRef.current?.seek(seg.start);
      setTime(seg.start);
      setPaused(false);
    }
  }, [time]);

  const onWordsRead = useCallback((n: number) => {
    setWordsRead(prev => prev + n);
  }, []);

  return (
    <View style={styles.screen}>
      <View style={styles.header}>
        <Text style={styles.wordmark}>
          Every
          <Text style={styles.wordmarkPill}>Word</Text>
        </Text>
        <Text style={styles.meta}>
          Words read along: <Text style={styles.metaStrong}>{wordsRead}</Text> of{' '}
          {countWords(captions)}
        </Text>
      </View>

      <View style={styles.card}>
        <Text style={styles.title}>The Two Pots</Text>
        <Text style={styles.attribution}>
          Aesop, read by LibriVox volunteers. Public domain. Captions generated
          with Amazon Transcribe.
        </Text>

        <View style={styles.captionArea}>
          <KaraokeCaptionsNative
            doc={captions}
            time={time}
            textStyle={styles.captionText}
            highlightColor={COLORS.highlight}
            highlightInk={COLORS.highlightInk}
            doneInk={COLORS.ink}
            upcomingInk={COLORS.muted}
            onWordsRead={onWordsRead}
          />
        </View>

        <View style={styles.progressRow}>
          <Text style={styles.meta}>{formatTime(time)}</Text>
          <View style={styles.progressTrack}>
            <View
              style={[
                styles.progressFill,
                {width: `${duration > 0 ? Math.min(100, (time / duration) * 100) : 0}%`},
              ]}
            />
          </View>
          <Text style={styles.meta}>{formatTime(duration)}</Text>
        </View>

        <View style={styles.buttonRow}>
          <TvButton
            label={paused ? 'Play' : 'Pause'}
            onPress={() => setPaused(p => !p)}
            preferred
            primary
          />
          <TvButton label="Read that line again" onPress={replayLine} />
          <TvButton
            label={slow ? 'Normal speed' : 'Slow down'}
            onPress={() => setSlow(s => !s)}
          />
        </View>
      </View>

      <Video
        ref={videoRef}
        source={media}
        paused={paused}
        rate={slow ? 0.8 : 1}
        progressUpdateInterval={100}
        onProgress={p => setTime(p.currentTime)}
        onLoad={l => setDuration(l.duration)}
        onEnd={() => setPaused(true)}
        style={styles.hiddenPlayer}
        audioOutput="speaker"
        playInBackground={false}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.bg,
    paddingHorizontal: '5%',
    paddingVertical: '4%',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  wordmark: {color: COLORS.ink, fontSize: 30, fontWeight: '700'},
  wordmarkPill: {
    backgroundColor: COLORS.highlight,
    color: COLORS.highlightInk,
  },
  card: {
    flex: 1,
    marginTop: 24,
    backgroundColor: COLORS.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.line,
    padding: 36,
  },
  title: {color: COLORS.ink, fontSize: 26, fontWeight: '600'},
  attribution: {color: COLORS.muted, fontSize: 14, marginTop: 6},
  captionArea: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  captionText: {
    fontSize: 44,
    fontWeight: '600',
    lineHeight: 66,
    color: COLORS.ink,
  },
  progressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  progressTrack: {
    flex: 1,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.line,
    overflow: 'hidden',
  },
  progressFill: {
    height: 6,
    backgroundColor: COLORS.primary,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 14,
    marginTop: 22,
  },
  button: {
    borderWidth: 2,
    borderColor: COLORS.line,
    backgroundColor: COLORS.surface,
    borderRadius: 10,
    paddingHorizontal: 22,
    paddingVertical: 12,
  },
  buttonFocused: {
    borderColor: COLORS.highlight,
    transform: [{scale: 1.06}],
  },
  buttonText: {color: COLORS.muted, fontSize: 18, fontWeight: '600'},
  hiddenPlayer: {width: 0, height: 0},
});
