import type { CaptionDoc } from "./types";

/**
 * WebVTT export.
 *
 * Two modes, and the difference is the whole point of this project:
 *
 * - Plain: one cue per segment. Standard captions that any player renders,
 *   so content passed through the EveryWord pipeline is usable everywhere,
 *   not only in our renderer.
 * - Karaoke: the same cues, with WebVTT inline timestamp tags before each
 *   word. This is a standard WebVTT feature, and it is exactly the
 *   word-by-word mechanism EveryWord exists to deliver, expressed in a
 *   format nobody has to adopt anything to read.
 *
 * Writing both is what makes the EveryWord caption format a superset
 * rather than a silo: word timings in, standard captions out.
 *
 * Platform note, discovered through the Amazon Devices Builder Tools MCP
 * server (see docs/BUILDER_TOOLS.md): Vega OS renders captions through the
 * W3C TextTrack API and a VTTCue polyfill, and VTTCue carries one
 * start/end pair per cue. Inline timestamp tags inside a cue payload are
 * not surfaced, so the native caption path can show a line at a time but
 * not a word at a time. That is precisely why EveryWord ships its own
 * renderer, and it is our clearest feature request for the platform.
 */

function vttTime(seconds: number): string {
  const ms = Math.max(0, Math.round(seconds * 1000));
  const h = Math.floor(ms / 3_600_000);
  const m = Math.floor((ms % 3_600_000) / 60_000);
  const s = Math.floor((ms % 60_000) / 1000);
  const milli = ms % 1000;
  const pad = (n: number, w = 2): string => String(n).padStart(w, "0");
  return `${pad(h)}:${pad(m)}:${pad(s)}.${pad(milli, 3)}`;
}

export interface WebVttOptions {
  /** Emit inline timestamp tags before each word (WebVTT karaoke). */
  karaoke?: boolean;
}

export function toWebVTT(doc: CaptionDoc, opts: WebVttOptions = {}): string {
  const lines: string[] = ["WEBVTT", ""];
  lines.push(
    `NOTE Generated by EveryWord (${doc.source.kind}${doc.source.model ? `, ${doc.source.model}` : ""}).`,
  );
  if (opts.karaoke) {
    lines.push("NOTE Word-level timings are expressed as WebVTT inline timestamp tags.");
  }
  lines.push("");

  for (const seg of doc.segments) {
    lines.push(String(seg.id + 1));
    lines.push(`${vttTime(seg.start)} --> ${vttTime(seg.end)}`);
    if (opts.karaoke && seg.words.length > 0) {
      // The first word needs no tag: the cue start already places it.
      const body = seg.words
        .map((w, i) => (i === 0 ? w.w : `<${vttTime(w.s)}>${w.w}`))
        .join(" ");
      lines.push(body);
    } else {
      lines.push(seg.text);
    }
    lines.push("");
  }
  return lines.join("\n");
}
